################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
USER \
driver/Libraries/infineon_libraries/Infra/Platform/Tricore/Compilers \
driver/Libraries/infineon_libraries/Service/CpuGeneric/If \
driver/Libraries/infineon_libraries/Service/CpuGeneric/StdIf \
driver/Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Bsp \
driver/Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Comm \
driver/Libraries/infineon_libraries/Service/CpuGeneric/SysSe/General \
driver/Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Math \
driver/Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Time \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Asc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Lin \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Spi \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Icu \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/PwmBc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/PwmHl \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/TPwm \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Timer \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cif/Cam \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cif/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/CStart \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Irq \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Trap \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Dma \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Dsadc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Rdc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dts/Dts \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dts/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Emem/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eray/Eray \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eray/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eth/Phy_Pef7071 \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eth/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fce/Crc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fce/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fft/Fft \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fft/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Flash/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tim/In \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Trig \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Hssl/Hssl \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Hssl/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/I2c/I2c \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/I2c/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Iom/Driver \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Iom/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Msc/Msc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Msc/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Mtu/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Multican/Can \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Multican/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Io \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5/Psi5 \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5s/Psi5s \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5s/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiMaster \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiSlave \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Scu/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Sent/Sent \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Sent/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Smu/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Src/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Timer \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Adc \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Std \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/_Impl \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/DataHandling \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/InternalMux \
driver/Libraries/infineon_libraries/iLLD/TC26B/Tricore/_PinMap \
driver/Libraries/seekfree_libraries/board \
driver/Libraries/seekfree_libraries/common \
driver/Libraries/seekfree_libraries \
driver/Libraries/seekfree_peripheral \
elab/3rd/rtt/rtthread_libraries/src \
elab/common \
elab/os/mcu_rtt \

